'use strict';

export const APP_NAME = 'Bidang Sarana dan Prasarana Operations Platform';
export const APP_VERSION = '1.11.1.2';
export const RELEASE_NAME = 'Identity Foundation — Custom Auth & Authenticated RTDB';

export const VERSION_HISTORY = [
  {
    version: '1.11.1.2',
    date: '2026-06-13',
    summary: 'Identity Foundation — Firebase Custom Auth & authenticated RTDB',
    highlights: [
      'Trusted per-user identity: login now calls the verifyPin Cloud Function (server-side PIN check) which mints a Firebase custom token with uid=username and an authoritative { role } claim, then signInWithCustomToken() establishes a real Firebase Auth session — the PIN login UX is unchanged',
      'verifyPin (functions/src/auth/verifyPin.js) activated from its v1.11.1.1 dormant skeleton: normalizes the username to match the /users key, reads the record via the Admin SDK, rejects unknown/inactive/archived users and PIN mismatches with a generic unauthenticated error (no enumeration), and never logs the PIN',
      'Write-through session cache: localStorage is now a cache of Firebase auth state hydrated by onAuthStateChanged (role from the token claim, displayName preserved from cache); getCurrentUser() keeps its synchronous signature so all ~70 existing consumers are untouched',
      'Auth-ready gate in app.js: a new startAuthenticatedSession() runs initUsersSync / stores / settings / initFirebaseSync / reminder timers only after authReady() resolves with a signed-in user — no RTDB access before authentication, eliminating permission_denied storms',
      'RTDB Security Rules Stage B: /.read and /.write now require auth != null (database.rules.json). No role or ownership restrictions yet. database.rules.stageA.json retained as the instant rollback to open rules',
      'AUTH_DIRECT_PIN break-glass flag (default OFF): window.AUTH_DIRECT_PIN or localStorage pbsi_auth_direct_pin restores the legacy client-side PIN path for emergency rollback (pair with Stage A rules); legacy login code retained',
      'Username audit (Phase 0 gate): 24 users audited, zero invalid usernames — uid=username is safe with no re-keying',
      'Deferred to later sub-versions: Role Rules, Ownership Rules, server-side Telegram, Push Notifications',
    ],
  },
  {
    version: '1.10.6',
    date: '2026-06-13',
    summary: 'Export PDF width fix + compact Request Review (Sprint 7D polish)',
    highlights: [
      'Export PDF is now genuinely content-width: the analytics toolbar button switched off the global full-width .btn-reimbursement (style.css forces width:100%) to the purpose-built .v2-analytics-export-btn (width:auto; display:inline-flex; flex:0 0 auto) — it sits inline beside Reset Filter instead of stretching across its own row',
      'Request Review redesigned to fit the viewport with no horizontal scrolling: the table now shows only the primary fields (Tanggal · Bidang · Tujuan · Status · Klasifikasi · Tata Kelola); secondary fields (Request ID · Pemohon · Driver · Kendaraan) move into an expandable per-row detail panel (tap the row chevron)',
      'Feels like an operational review, not a database viewer — narrower modal, compact columns with ellipsis, tap-to-expand details',
      'Presentation only — governance model, engine gate, and all analytics values unchanged; parity/trend/insights/recommendations harnesses still pass',
    ],
  },
  {
    version: '1.10.5',
    date: '2026-06-13',
    summary: 'Export hub restore + Request governance (Sprint 7D follow-up)',
    highlights: [
      'Export PDF is a compact, content-width utility button living in the filter/action row (Rentang · Driver · Kendaraan · Bidang · Reset · Export PDF) — icon + label, semantic tokens, distinct in light vs dark, no full-width strip',
      'Export Center restored as the long-term reporting hub — redesigned as a calm, secondary, future-ready format LIST (Laporan PDF available; Excel & Cetak "Segera hadir") instead of the old full-width button banner; PDF shares the same exportAnalyticsReport() path and on-screen data, and it does not compete with the keynote hero',
      'Analytics Governance now covers driver_requests as well as assignments: the engine routes BOTH record kinds through the same filterEligible() gate, so an excluded request leaves every downstream aggregate',
      'Data Quality Center gains "Tinjau Request" alongside "Tinjau Tujuan" and "Tinjau Assignment" — a record-level review of driver_requests (ID · Tanggal · Pemohon · Bidang · Driver · Kendaraan · Tujuan · Status) filterable by Date Range / Driver / Kendaraan / Bidang / Status / analytics eligibility, with ID/destination/requester search',
      'Requests support the same four governance actions as assignments — Tandai Data Produksi · Tandai Data Uji · Keluarkan Dari Analytics · Pulihkan Ke Analytics — writing an audited request.governance block ({ classification, analyticsEligible, classifiedBy, classifiedAt }); logged via request_classified',
      'Excluded requests remain in Firebase, editable and operationally visible, but no longer participate in KPIs / Trends / Insights / Recommendations / Health Score / Analytics Export / future AI analytics — no deletion, fully reversible',
      'Governance remains the same opt-in gate (absence of a governance block ⇒ production); no analytics calculation, KPI, trend, insight, or recommendation logic changed — parity/trend/insights/recommendations harnesses still pass',
    ],
  },
  {
    version: '1.10.4',
    date: '2026-06-13',
    summary: 'Analytics Governance & UX Polish (Sprint 7D)',
    highlights: [
      'Export PDF is now a compact utility action, not a banner: the full-width "Export Center" section is removed and Export PDF lives solely as a quiet, theme-aware icon+label button in the filter/action row (Rentang · Driver · Kendaraan · Bidang · Reset · Export PDF) — semantic surface/border/text tokens, distinct in light vs dark, never full width',
      'Data Quality Center now governs records, not just names: a new "Tinjau Assignment" review sits alongside "Tinjau Tujuan" — the first operational UI for the Analytics Governance Layer',
      'Assignment Review screen: a compact governance table (ID · Tanggal · Driver · Kendaraan · Bidang · Tujuan · Status · Klasifikasi) filterable by Date Range / Driver / Kendaraan / Bidang and by analytics eligibility, with searchable ID/destination lookup',
      'Record-level governance actions — Tandai Data Produksi · Tandai Data Uji · Keluarkan Dari Analytics · Pulihkan Ke Analytics — write an audited assignment.governance block ({ classification, analyticsEligible, classifiedBy, classifiedAt }); each change is logged via assignment_classified',
      'Excluded assignments remain in the database, visible and editable operationally, but no longer participate in Analytics / Trends / Insights / Recommendations / Health Score (the engine already filters at its boundary via filterEligible) — no deletion, fully reversible',
      'Claude Design language for the review UI: compact table, subtle hairlines, semantic status & classification chips, no emoji; mobile-friendly (filters stack, table scrolls horizontally)',
      'No analytics calculation, KPI, trend, insight, or recommendation logic changed — governance is the same opt-in gate shipped in Sprint 0 (absence of a governance block still means production); parity/trend/insights/recommendations harnesses still pass',
    ],
  },
  {
    version: '1.10.3',
    date: '2026-06-13',
    summary: 'Analytics Experience polish (Sprint 7C)',
    highlights: [
      'Resource Analytics density: tighter vertical spacing across panels (subsections, list/breakdown rows, cards) for a professional data-workspace feel with less scrolling — readability preserved',
      'Bidang Analytics now leads with distance: rankings, summaries, highlights, and the table show "{jarak} km" as the primary value with assignment count as supporting context (distance surfaced from existing distanceTravelled data in the presentation layer — no analytics computation change)',
      'Export PDF button redesigned: smaller, quieter, theme-aware utility action (semantic surface/border/text tokens — distinct in light vs dark) instead of an oversized accent button; the Export Center action is de-emphasized to match',
      'Removed duplicate page copy: the Analytics header now uses an analytics-specific description ("Analisis kinerja operasional, utilisasi sumber daya, dan tren aktivitas.") instead of repeating the Administration-level context',
      'Presentation only — no KPI, trend, insight, recommendation, or chart-dataset changes; parity/trend/insights/recommendations harnesses still pass',
    ],
  },
  {
    version: '1.10.2',
    date: '2026-06-12',
    summary: 'Analytics Experience V2 — Claude Design visual language',
    highlights: [
      'Analytics migrated to the approved Claude Design visual language: a typography-first, de-boxed, Apple-style operational-intelligence experience (replaces the Sprint-7A card-in-card layout). Scoped under .v2-analytics-claude — the rest of the app is unchanged',
      'Keynote executive hero: a derived operational-health verdict ("Operasi berjalan sehat") + a 0–100 health score in a draw-animated ring gauge + three big stats with real period-over-period deltas. The score is computed in the presentation layer purely from existing KPIs (completion/open/cancellation rates + Priority-1 finding count) — no engine change, no fabricated data',
      'Custom SVG icon system (no emoji anywhere): a single consistent outline stroke set ported from the prototype replaces every emoji glyph across KPIs, tabs, insights, and export',
      'De-boxed sections with eyebrow headers + hairline dividers; editorial highlights trio that deep-links into Resource tabs; premium segmented control for Resource Analytics; Operational Health rendered as a divider-based insight list (severity + Wawasan/Rekomendasi tags) instead of nested boxes',
      'Calm micro-animations: count-up numbers, ring-gauge draw, section fade-up, insight stagger, panel-enter, attention pulse — all 200–1200ms and disabled under prefers-reduced-motion / [data-anim="off"]',
      'Proper dark mode via scoped semantic tokens (not an inverted light mode); Archivo/Manrope/JetBrains Mono fonts applied only within the analytics scope; mobile keeps the hero, stacks stats/highlights, fills the seg control full-width, no horizontal scroll',
      'Presentation only — engine/model/insights/recommendations/trends modules and every analytics value, chart dataset, and canvas id are untouched; parity/trend/insights/recommendations harnesses still pass',
    ],
  },
  {
    version: '1.10.1',
    date: '2026-06-12',
    summary: 'Analytics Experience V2 — Claude Design migration',
    highlights: [
      'Analytics migrated to the Claude Design experience: the former flat list of sections is re-composed into a 6-section operational-intelligence dashboard — Executive Summary, Operational Trends, Operational Health, Resource Analytics, Data Quality Center, Export Center — each wrapped in an elevated section card with a clear hierarchy (eyebrow + H2 + description)',
      'Operational Health (new): merges the Insight Engine and Recommendation Engine outputs into one prioritized surface, grouped Prioritas 1 → 3 (highest first) with each card tagged Wawasan or Rekomendasi; uses the priority each engine already emits',
      'Resource Analytics (new): Driver / Kendaraan / Bidang / Tujuan / Jarak Tempuh consolidated into one section with a segmented tab control — one panel at a time; Chart.js charts in hidden panels are resized on show so they render correctly',
      'Export Center (new): a dedicated section with a working PDF export (shares exportAnalyticsReport with the header button) and prepared Excel / Print placeholders; the header Export PDF button is retained',
      'Presentation-only: no analytics logic, KPI, chart dataset, insight, recommendation, or trend value changed — the engine modules (engine/model/insights/recommendations/trends) are untouched and the existing parity/trend/insights/recommendations harnesses still pass',
      'Mobile: section cards stack, tabs wrap (no horizontal scrolling), export buttons go full-width at ≤600px',
    ],
  },
  {
    version: '1.10.0',
    date: '2026-06-12',
    summary: 'Trend Engine Foundation',
    highlights: [
      'Analytics V2 now answers "what changed?" — a deterministic Trend Engine compares the current period to the previous equal-length period using KPIs the engine already computes. No AI, no prediction, no new KPI formulas; trend analysis is strictly additive (parity-check confirms no existing analytics value changes)',
      'Period comparison foundation (js/analytics/analytics-period.js): derivePreviousPeriod() maps each date range to its adjacent, non-overlapping prior window (today→yesterday, 7d→prior 7d, 30d→prior 30d, 90d→prior 90d); "Semua Data" has no fixed length → no comparison',
      'Engine isolation (additive): computeAnalyticsModel gains an optional ctx.windowEnd upper bound and ctx.previousModel — the previous model is computed with a shifted clock + windowEnd so current-period records never leak into the prior window; model.trends is populated before the Insight/Recommendation layers in a single pass',
      'Trend contract (js/analytics/analytics-trends.js): { current, previous, delta, percentChange, direction, tone } for the 4 required KPIs — Total Assignments, Completion Rate, Open Rate, Cancellation Rate; direction is raw movement, tone is goodness (up is good for completion, bad for open/cancellation)',
      'KPI trend indicators: Completion Rate and Total Assignments overview cards show a period-over-period badge (▲/▼ %), colored by tone; renderTrendIndicator gains optional tone-based coloring (an up-arrow on Open Rate reads red)',
      'Operational Trends section activated (was a placeholder): a 4-card grid of trend comparisons with graceful states — available (arrows), insufficient history (neutral + note), and comparison-unavailable for "Semua Data" — never a fabricated trend',
      'Trend-aware Insights & Recommendations: optional, guarded references appear only when valid trend data exists (e.g. "Tingkat penyelesaian naik 50% dibanding periode sebelumnya"), each tagged with a "(Trend)" source for traceability; without a previous period, output is unchanged',
      'Verification: Analytics-V2/trend-check.mjs proves deterministic output, correct direction/percent/tone, previous-period isolation (no leakage), missing-history handling (no divide-by-zero), and additive-only behavior; parity/insights/recommendations harnesses still pass',
    ],
  },
  {
    version: '1.9.3',
    date: '2026-06-11',
    summary: 'Analytics Export Foundation',
    highlights: [
      'Analytics Summary Report — first Analytics PDF, built entirely on the v1.9.2 Document Generation Foundation (DocumentEngine · TemplateRegistry · PdfExporter · DocumentViewer · PrintManager). No new PDF pipeline; no html2canvas/jsPDF/browser-print',
      'New template js/docs/templates/analytics-summary.js: 6 sections — Operational Summary (Completion Rate, Total Assignments, Active Drivers, Active Vehicles), Driver Analytics (most/least active + counts), Vehicle Analytics (most used, idle units + counts), Bidang Analytics (most active, request & assignment counts), Filter Snapshot, Report Metadata (Generated At / By / APP_VERSION)',
      'Export PDF button added to the Analytics toolbar; report data is snapshotted from the live analytics compute (refreshAnalyticsDisplay) so the PDF matches exactly what is on screen — no recomputation, no drift',
      'Executive-friendly, text-and-tables only (no charts/graphs/images/canvas), A4 portrait, deterministic across Desktop / Android / iPhone / PWA — proves the framework reuse claim: a new report = one template file + one register() + one integration point',
      'Second production template on the engine (after Reimbursement), validating the Document Generation Foundation as the standard for future Audit, Asset, Engineering, and AI-generated reports',
    ],
  },
  {
    version: '1.9.2',
    date: '2026-06-11',
    summary: 'Document Generation Foundation',
    highlights: [
      'New Document Generation Framework (js/docs/*) — reusable PDF engine for all current and future reports (Reimbursement, Analytics, Audit, Asset, Engineering, AI). Hybrid C-now / D-later: pdfmake client-side today, swappable to a server-side Puppeteer backend later behind the same Blob interface',
      'PDF-first architecture: documents are computed in pure JS from declarative templates, never rasterized from the DOM or paginated by the browser print engine — output is deterministic and byte-identical across Desktop, Android, iPhone, and installed PWA',
      'DocumentEngine · TemplateRegistry · PdfExporter (PdfmakeBackend + PuppeteerBackend stub) · DocumentViewer · PrintManager · doc-theme — one engine, one reusable preview/print/share modal, one shared visual language; APP_VERSION injected centrally so no document hardcodes a version again',
      'Reimbursement is the first production template: js/reimbursement.js reduced from 1047 → 155 lines (domain logic only), delegating render/preview/print/download/share to the engine; public API (printReimbursementForm, closePdfViewer, calculateOvertimeStatus) unchanged',
      'Removed the four legacy reimbursement paths: html2canvas raster, jsPDF assembly, iframe + window.print(), and viewport zoom-scaling — eliminating the mobile page-2 / 11 MB / corrupt-download failure class entirely',
      'Real PDF output: text-based, ~20–80 KB per form (was ~11 MB on mobile), opens in any PDF reader; single-page A4 guaranteed by fixed-geometry layout, not CSS print hacks',
      'Cleanup: removed orphaned #modalPdfViewer markup (index.html) and the dead PDF Viewer Modal stylesheet incl. pdf-slide-up / pdf-scale-in / pdf-spin keyframes (platform.css); dropped html2canvas and jsPDF CDN dependencies',
      'framework-poc.html: standalone cross-platform verification harness — fixed sample data, timestamp-normalized SHA-256 fingerprint, page-count guard, and device diagnostics; Phase 1.5 + Phase 2 verified on Desktop / Android / iPhone / PWA before migration',
    ],
  },
  {
    version: '1.9.1.1',
    date: '2026-06-10',
    summary: 'PWA Install Experience',
    highlights: [
      'Global install onboarding — visible to all roles, not just admins in Configuration Center',
      'Android: persistent bottom install banner (#pwaInstallBanner) auto-shown 3 s after page load when beforeinstallprompt is available; "Instal" CTA wraps triggerInstallPrompt(); auto-hidden on appinstalled / standalone mode change',
      'iPhone: iOS Add-to-Home-Screen onboarding modal (existing showIOSInstallModal) auto-shown 3 s after page load on ios-safari',
      'Dismiss persistence: localStorage key pbsi_pwa_install_dismissed stores timestamp; suppressed for 7 days after dismiss or after iOS modal auto-show; resets after TTL',
      '_bannerCheckDone flag: if beforeinstallprompt fires after the 3-s check, the banner shows immediately (handles slow Chrome instability detection)',
      'display-mode change listener: hides install banner when app transitions to standalone mode',
      'platform.css: .v2-pwa-install-banner (fixed bottom, z-index 9998), .v2-pwa-install-icon (crimson 42×42 rounded square), .v2-pwa-install-name, .v2-pwa-install-hint, .v2-pwa-install-cta, .v2-pwa-install-close; dark-mode; ≤400px hides hint text',
      'No changes to Configuration Center PWA diagnostics group',
    ],
  },
  {
    version: '1.9.1',
    date: '2026-06-10',
    summary: 'Advanced PWA Foundation',
    highlights: [
      'service-worker.js: cache-first strategy for static assets (CSS, JS, icons, manifest, fonts); network-first with offline.html fallback for navigation; network-only for Firebase origins',
      'offline.html: standalone offline fallback page — crimson icon, "Sarpras Operations" label, "Tidak ada koneksi internet. / Silakan periksa jaringan Anda dan coba kembali.", Coba Lagi button; dark-mode-aware; zero external deps',
      'Update Detection: when a new SW is installed and waiting, shows bottom banner "Versi baru tersedia. [Refresh Sekarang]"; button sends SKIP_WAITING to the waiting worker then reloads the page on controllerchange',
      'PWA Diagnostics extended: Configuration → Progressive Web App now shows Service Worker (Aktif/Mendaftar…/Tidak Didukung/Gagal), Cache (N aset), Versi (vX.Y.Z from config), Update Tersedia (Ya/Tidak with amber warning color)',
      'SW state tracked in pwa.js: swStatus, swUpdateAvailable, swCacheCount, appVersion — all included in getPWAState() snapshot and trigger registerPWAStateListener callbacks',
      'Cache count refreshed asynchronously after SW activates and after controllerchange; shown live in diagnostics panel',
      'Cache cleanup on activate: old sarpras-cache-* versions deleted when new SW takes control — no stale caches left behind',
      'platform.css: .v2-pwa-update-banner (fixed bottom bar, safe-area-inset-bottom), .v2-pwa-update-btn, .v2-pwa-stat--warn, .v2-pwa-stat-divider; mobile: banner stacks vertically, button full-width',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-06-10',
    summary: 'PWA Foundation',
    highlights: [
      'manifest.json: name "Sarpras Operations", short_name "Sarpras", display standalone, orientation portrait-primary, theme_color #A8292F, background_color #FBFAF8',
      'PWA Icons: 192×192 and 512×512 PNGs generated via puppeteer — bold white "S" on crimson background with accent underbar; both registered as any + maskable',
      'js/pwa.js: self-contained PWA module — beforeinstallprompt capture at module load time, appinstalled listener, display-mode change listener, iOS/Android/Chrome platform detection',
      'Install Detection: isInstalled (matchMedia standalone + navigator.standalone), platform detection for ios-safari / android-chrome / desktop-chrome / other',
      'Android/Chrome Install Flow: triggerInstallPrompt() wraps beforeinstallprompt.prompt() + userChoice; shows "Install Sarpras Operations" button in PWA Settings only when canInstall',
      'iOS Safari Install Flow: showIOSInstallModal() creates a 3-step onboarding modal (Share → Add to Home Screen → Add); shown only on iOS Safari when not already installed',
      'Installation Status: when display-mode:standalone detected, hides install actions and shows "✓ Aplikasi Terinstal" badge',
      'PWA Settings in Configuration Center: read-only group with Status, Platform, Install Tersedia, Display Mode; refreshes live via registerPWAStateListener',
      'Branding Migration: HTML title updated to "Sarpras · Jadwal Driver Operasional"; app-splash updated to "Sarpras"; manifest, apple-mobile-web-app-title, application-name all use Sarpras branding',
      'index.html: manifest link, apple-touch-icon, meta theme-color, apple-mobile-web-app-capable/status-bar-style/title, application-name, description all added',
      'scripts/generate-icons.js: Node.js puppeteer script for reproducing icons; renders HTML template at exact pixel size; deterministic output',
      'No service worker, no offline mode, no push notifications — foundation only',
    ],
  },
  {
    version: '1.8.4.2',
    date: '2026-06-10',
    summary: 'Analytics Data Quality Center Enhancements',
    highlights: [
      'Data Quality Statistics bar: 4 stat cards — Potensi Duplikasi, Warning Diabaikan, Alias Aktif, Duplikasi Diselesaikan; warn/ok color states',
      'Skip/Dismiss Warning: Abaikan button on each unresolved pair; stores dismisser name + timestamp to /settings/analyticsQuality/dismissedWarnings/{type}/{pairKey}; does NOT create alias or modify data',
      'Restore Ignored Warnings: Warning Diabaikan section lists dismissed pairs with dismisser, date, and Tampilkan Lagi button; warning_restored audit log',
      'Tinjau Semua Tujuan: review modal showing all destinations from filtered assignments with Name, Count, Normalized Key; searchable; sorted most-used first',
      'Manual Merge from Review Modal: select exactly 2 destinations via checkbox; Gabungkan Terpilih opens alias resolution modal pre-filled with both values',
      'Alias Impact Preview: Gabungkan button passes countA/countB; modal shows "A: N asg + B: M asg → Gabungan: N+M asg" before saving',
      'Bulk Alias Visibility: Kelola Alias table gains Penggunaan (usage count) and Dibuat (created date) columns; created date tooltip shows creator name and ISO timestamp',
      'Alias schema upgraded: stored as { canonical, createdAt, createdBy } object; backward-compatible with legacy plain strings via _getAliasCanonical()',
      '_dismissDqWarning / _restoreDqWarning: new async helpers; log warning_dismissed / warning_restored audit actions',
      'initDestinationReviewModal / openDestinationReviewModal / _renderDestReviewList: new modal and rendering pipeline for manual destination review workflow',
      'window._analyticsFilteredAsg: exposes current filtered assignments for destination review modal without requiring re-query',
      'Mobile: stats bar collapses to 2×2; pair actions wrap; Kelola Alias Usage/Dibuat columns hidden on ≤600px',
    ],
  },
  {
    version: '1.8.4.1',
    date: '2026-06-10',
    summary: 'Analytics Alias Resolution',
    highlights: [
      'Data Quality Resolution Center: replaces warning-only block with actionable resolution workflows; each detected pair shows a "Gabungkan" button',
      'Alias Resolution Layer: /settings/analyticsAliases/{type}/{normalizedKey} → canonical value; applied before analytics computation — raw operational records untouched',
      'Resolution Modal: radio selection of canonical value (A / B / Custom text input); saves to Firebase, logs audit action, triggers immediate analytics recalculation',
      'Alias Resolution in Destination Analytics: occurrences of aliased names are counted under the canonical key, reducing duplicate destination entries',
      'Alias Resolution in Bidang Analytics: bidang names resolved through alias map before frequency counting',
      'Alias Active Indicator: resolved pairs show "✓ Alias Aktif" badge with canonical value instead of Gabungkan button',
      'Kelola Alias table: lists all existing aliases (alias key, canonical value, type) with inline Hapus action',
      'Delete Alias: removes mapping from Firebase; does NOT modify assignments or requests; analytics recalculates automatically',
      'Audit Logging: alias_created and alias_deleted actions logged with type, aliasKey, canonical, actor, timestamp',
      'Auto-refresh: registerSettingsChangeListener triggers refreshAnalyticsDisplay() when alias settings change',
      'Firebase schema: /settings/analyticsAliases/destinations, /drivers, /vehicles, /bidang (each: normalizedKey → canonicalString)',
      'New CSS: .v2-dq-center, .v2-dq-pair-list, .v2-dq-pair-row, .v2-dq-type-badge, .v2-dq-merge-btn, .v2-dq-resolved-badge, .v2-dq-alias-table, .v2-alias-modal-box, .v2-alias-radio-row, .v2-alias-custom-input, .v2-alias-modal-footer',
      'Mobile: pair rows wrap, Gabungkan and Alias Aktif full-width on ≤600px; modal max-width 100%',
    ],
  },
  {
    version: '1.8.4',
    date: '2026-06-10',
    summary: 'Analytics Refinement & Data Quality',
    highlights: [
      'Task 1 — Destination Normalization: _normDestKey() collapses trim/lowercase/dash-variants/multi-space/trailing-punct into a canonical key; display label preserved as most-frequent raw value; duplicate destination entries now merged in analytics',
      'Task 2 — Destination Similarity Detection: _strSimilarity() (Levenshtein ratio) + _detectSimilarPairs() identify likely-duplicate names at ≥0.75 similarity; warnings-only, no auto-merge',
      'Task 3 — Data Quality Warnings: collapsible "Peringatan Kualitas Data" section appears when similar destinations / bidang / driver / vehicle names are detected; informational only, no data mutation',
      'Task 4 — Completion Metrics Merge: Completion Rate + Open Rate KPIs moved into Ringkasan Operasional; separate "Kualitas Penyelesaian" section removed — reduces scroll depth',
      'Task 5 — Bidang Cleanup: requesterName null / undefined / empty-string entries skipped in bidang analytics — prevents "-" from appearing as a ranked bidang',
      'Task 6 — Filter Chip UX: date range chip uses neutral --date modifier (muted, surface bg); entity filter chips use --active modifier (accent color) — visual distinction between default context and active filters',
      'New CSS: .v2-analytics-filter-chip--date, .v2-analytics-filter-chip--active, .v2-dq-details, .v2-dq-summary, .v2-dq-count, .v2-dq-hint, .v2-dq-list, .v2-dq-item, .v2-dq-type, .v2-dq-pair, .v2-dq-note',
    ],
  },
  {
    version: '1.8.3',
    date: '2026-06-09',
    summary: 'Analytics UX Polish',
    highlights: [
      'Feature 1 — Active Filter Summary: chips displayed below toolbar showing active date range and any entity filters (Driver/Kendaraan/Bidang)',
      'Feature 2 — Reset Semua Filter: one-click button resets all four filters to defaults (30 Hari, Semua Driver, Semua Kendaraan, Semua Bidang)',
      'Feature 3 — Top Performer Badges: #1 Driver, #1 Kendaraan, #1 Bidang badges shown on the top-ranked row in each breakdown',
      'Feature 4 — Contextual Empty States: per-section messages (driver: "Tidak ada assignment pada periode yang dipilih.", vehicle: "Tidak ada data kendaraan yang sesuai dengan filter aktif.", bidang: "Tidak ada permintaan bidang pada rentang waktu ini.")',
      'Feature 5 — Analytics Sections: cards grouped under 5 labelled section headers (Ringkasan Operasional / Utilisasi Driver / Utilisasi Kendaraan / Analisis Bidang / Kualitas Penyelesaian); Inactive Resources absorbed into Driver and Vehicle sections',
      'Feature 6 — Insight Highlights: up to 3 plain-text highlights at the top (Driver paling aktif, Kendaraan paling sering digunakan, Bidang dengan permintaan terbanyak)',
      'New CSS: .v2-analytics-filter-summary, .v2-analytics-filter-chip, .v2-analytics-reset-btn, .v2-analytics-insights, .v2-analytics-sections, .v2-analytics-section, .v2-analytics-section-header, .v2-analytics-top-badge',
      'Mobile: filter chips wrap, reset button full-width on ≤600px, insight highlights stack vertically',
    ],
  },
  {
    version: '1.8.2',
    date: '2026-06-09',
    summary: 'Analytics Deep Metrics',
    highlights: [
      'Module 1 — Driver Workload Distribution: workload % per driver, relative classification (Seimbang / Melebihi / Di Bawah) using mean ± stdDev — no hardcoded thresholds',
      'Module 2 — Vehicle Utilization: utilization share % per vehicle added to breakdown',
      'Module 3 — Inactive Resources: active drivers with 0 assignments and active vehicles with 0 usage in selected period, sorted alphabetically',
      'Module 4 — Destination Analytics: top 10 destinations by frequency; module hidden gracefully when no destination data exists',
      'Module 5 — Bidang Demand Analysis: request share % and assignment share % per bidang; most active and least active bidang KPIs',
      'Module 6 — Completion Quality: Open Assignment Rate %, Selesai vs Total ratio, alongside existing Completion Rate',
      'All 7 cards respect all 4 active filters (date, driver, vehicle, bidang)',
      'New CSS: .v2-analytics-wl-badge (balanced/over/under/idle), .v2-analytics-breakdown-pct, .v2-analytics-subtitle--mt',
      'NaN-safe: all percentages guard against zero-division; empty states on every breakdown section',
    ],
  },
  {
    version: '1.8.1',
    date: '2026-06-09',
    summary: 'Analytics Filters',
    highlights: [
      'Four filter controls: Date Range, Driver, Vehicle, Bidang — rendered as v2-admin-filter selects',
      'Date Range options: Hari Ini / 7 Hari / 30 Hari (default) / 90 Hari / Semua Data',
      'Driver filter: populated from /drivers (active, non-archived only)',
      'Vehicle filter: populated from /vehicles (active, non-archived only)',
      'Bidang filter: built dynamically from unique requesterName values in requests[]',
      'Filters apply consistently to all 5 modules: Assignment, Driver, Vehicle, Bidang, Completion Analytics',
      'Overview cards (Completion Rate, Total Assignments, Driver Bertugas, Kendaraan Digunakan) update on every filter change',
      'Global empty state shown when no matching assignments or requests exist — replaces zero-filled module cards',
      'Per-breakdown empty state shown inside individual cards when breakdown list is empty for the active period',
      'Filter state persists within session (analyticsDateRange, analyticsDriverFilter, analyticsVehicleFilter, analyticsBidangFilter)',
      'Architecture: renderV2AdminAnalytics() populates dropdowns; refreshAnalyticsDisplay() computes + renders — filter changes only call refreshAnalyticsDisplay()',
      'Mobile: all 4 filters wrap via flex-wrap on v2-admin-toolbar — no horizontal scroll',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-06-09',
    summary: 'Analytics Foundation',
    highlights: [
      'Analytics section added to Administration Workspace (after Konfigurasi)',
      'Module 1 — Assignment Analytics: Total, Selesai, Berlangsung, Dijadwalkan, Dibatalkan',
      'Module 2 — Driver Utilization: Active drivers, Most/Least active, per-driver trip breakdown',
      'Module 3 — Vehicle Utilization: Active vehicles, Most/Least used, per-vehicle trip breakdown',
      'Module 4 — Bidang Analytics: Top requesting bidang ranked by request count and assignment count',
      'Module 5 — Completion Analytics: Completion rate %, Open assignments, Completed assignments',
      'Overview cards: Completion Rate, Total Assignments, Driver Aktif, Kendaraan Aktif',
      'No AI, no predictions, no charts — foundation KPIs from existing collections only',
      'Mobile-first: single-column stacking on ≤720px via v2-analytics-groups grid',
      'Section visibility bug fixed: users/drivers/vehicles tabs now properly hide audit section on switch',
    ],
  },
  {
    version: '1.6.2',
    date: '2026-06-09',
    summary: 'Security & Source Consolidation',
    highlights: [
      'Telegram bot token removed from index.html — loaded from Firebase /settings/telegram/botToken at runtime',
      'VEHICLES map in drivers.js demoted to internal fallback; all callers now use getVehicleColor() via vehicles-store',
      'DEFAULT_DRIVERS fallback rendering retired from timeline.js and requests.js; drivers-store is the only source',
      'VEHICLE_PLATES map removed; reimbursement.js now reads plateNumber directly from vehicles-store cache',
      'validation.js: KNOWN_VEHICLE_NAMES and KNOWN_DRIVER_NAMES replaced with live getActiveVehicleNames() / getActiveDriverNames() calls',
      'New exports: setTelegramBotToken (telegram.js), getVehicleColorByName + getActiveVehicleNames (vehicles-store.js), getActiveDriverNames (drivers-store.js)',
    ],
  },
  {
    version: '1.6.1',
    date: '2026-06-09',
    summary: 'Audit Center UX Polish',
    highlights: [
      'Human-readable audit summaries',
      'Business-friendly activity details',
      'Collapsible technical JSON payload',
      'Improved audit detail modal UX',
      'Mobile-friendly audit viewer',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-06-09',
    summary: 'Audit Center Foundation',
    highlights: [
      'Audit Center workspace',
      'Audit log explorer',
      'Category filtering',
      'Actor filtering',
      'Audit detail viewer',
      'Legacy log compatibility',
    ],
  },
  {
    version: '1.5.3.1',
    date: '2026-06-09',
    summary: 'Archived Records Searchability Fix',
    highlights: [
      'Bug fix: archived entities now discoverable through search in Users, Drivers, and Vehicles lists',
      'Filter = All: includes archived records when a search query matches them; shows Archived badge',
      'Filter = All with no search query: behaviour unchanged — archived records hidden by default',
      'Filter = Active/Inactive/Archived: unchanged, each shows only its respective state',
      'Root cause: status filter previously excluded archived records before search executed; fix evaluates search first',
    ],
  },
  {
    version: '1.5.3',
    date: '2026-06-09',
    summary: 'Archive & Safe Deletion Framework',
    highlights: [
      'Three-state lifecycle for Users, Drivers, and Vehicles: Active → Inactive → Archived',
      'Archive: sets archived=true, archived=true hides entity from all lists and dropdowns',
      'Restore: clears archived/archivedAt only — entity returns as Inactive, admin must re-activate',
      'Permanent Delete: only available when archived===true AND reference count === 0',
      'Reference counting from in-memory assignments[] and requests[] — no additional Firebase reads',
      'Delete confirmation modal requires typing "DELETE" before proceeding',
      'Status filter "Diarsipkan" option added to Users, Drivers, and Vehicles toolbars',
      'Overview cards and stats chips exclude archived from totals; show archived count when >0',
      'Vehicle validation fix: plate numbers must be unique (not vehicle names); multiple vehicles may share a model name',
      'Plate uniqueness: case-insensitive, whitespace-stripped comparison; empty plates always allowed',
      'Last active admin guard extended to archiveUser() — cannot archive the last active admin',
      'Restore does NOT auto-reactivate — prevents unintended activation of long-inactive entities',
    ],
  },
  {
    version: '1.5.2',
    date: '2026-06-09',
    summary: 'Vehicle Management Workspace',
    highlights: [
      'Vehicle Management module live in Administration Workspace (replaces placeholder)',
      'Feature 1: Overview cards — Total Vehicles, Active Vehicles, Inactive Vehicles',
      'Feature 2: Toolbar — Search by name/plate, Status Filter (All/Active/Inactive), Tambah Kendaraan',
      'Feature 3: Vehicle list with Name, Plate Number, Capacity, Color Preview, Active Status, and actions',
      'Feature 4: Create Vehicle form — Name, Plate Number, Capacity, Timeline Color (picker), Active toggle',
      'Feature 5: Edit Vehicle — all fields editable, updatedAt maintained',
      'Feature 6: Deactivate Vehicle — soft deactivate only (active=false + inactiveAt), never deletes',
      'Feature 7: Reactivate Vehicle — sets active=true + inactiveAt=null',
      'vehicles-store.js: createVehicle, updateVehicle, deactivateVehicle, reactivateVehicle, registerVehiclesChangeListener',
      'Firebase /vehicles introduced as source of truth; seeded from existing VEHICLES map on first load',
      'Phase A compatibility: existing hardcoded vehicle config unchanged; Timeline/Assignments/Requests unaffected',
      'Duplicate active vehicle name validation prevents conflicting records',
    ],
  },
  {
    version: '1.5.1',
    date: '2026-06-09',
    summary: 'Driver Management Stabilization',
    highlights: [
      'Bug fix: deactivated/created drivers now reflected in assignment and request driver dropdowns without page reload',
      'Bug fix: initDriverSelect() no longer accumulates change listeners — listener registered once, options rebuilt on driver change',
      'Bug fix: refreshDriverSelect() exported from drivers.js; called by drivers-store listener in app.js',
      'Bug fix: requests.js self-registers driver change listener — #requestFieldDriver kept in sync via PBSI Select MutationObserver',
      'Bug fix: removed stale explicit renderV2AdminWorkspace() from handleDriverFormSubmit and toggle handler — Firebase path was rendering with pre-update cache',
      'Bug fix: driver form modal toggle no longer stretches full-width — form-group flex-stretch overridden via align-self:flex-start',
      'Bug fix: toggle status label (Aktif/Nonaktif) now updates dynamically on change and on modal open',
      'Bug fix: Administration Workspace reachable on mobile — sidebar Admin Panel button navigates to V2 workspace',
      'Bug fix: V1 openUsersListModal no longer fires from sidebar button when V2 shell is active',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-06-09',
    summary: 'Driver Management Workspace',
    highlights: [
      'Driver Management module live in Administration Workspace (replaces placeholder)',
      'Feature 1: Overview cards — Total Drivers, Active Drivers, Linked Accounts',
      'Feature 2: Toolbar — Search by name/phone, Status Filter (All/Active/Inactive), Tambah Driver',
      'Feature 3: Driver list with Name, Phone, Active Status, Linked Account, and actions',
      'Feature 4: Create Driver form — Name, Phone, Linked User (optional), Active toggle',
      'Feature 5: Edit Driver — all fields editable, legacyNames preserved for backward compat',
      'Feature 6: Deactivate Driver — sets active=false + inactiveAt, never deletes',
      'Feature 7: Reactivate Driver — sets active=true + inactiveAt=null',
      'drivers-store.js: createDriver, updateDriver, deactivateDriver, reactivateDriver, registerDriversChangeListener',
      'Firebase CRUD via updateFirebaseData; local-only fallback when Firebase not configured',
      'Duplicate active name validation prevents conflicting driver records',
      'legacyNames preserved on rename for backward compatibility with assignments/timeline',
      'Real-time driver list refreshes via Firebase subscription unchanged',
    ],
  },
  {
    version: '1.4.1',
    date: '2026-06-07',
    summary: 'PBSI Date Picker Component',
    highlights: [
      'Custom PBSI Date Picker replaces all 5 native date inputs',
      'Targets: filterDate (header nav), fieldDate, fieldEndDate, requestFieldStartDate, requestFieldEndDate',
      'Flatpickr 4.6.13 vendored locally (vendor/flatpickr.min.js + flatpickr.min.css)',
      'Indonesian locale inline — weekday/month names in Bahasa Indonesia',
      'Start date presets: Hari Ini · Besok · Lusa · Pilih Tanggal',
      'End date presets: Sama Hari · +1 Hari · +2 Hari · Pilih Tanggal (relative to start date)',
      'Smart preset highlight — active state auto-detects which preset matches current value',
      'Calendar appended to document.body (z-index 360) — escapes modal stacking contexts',
      'PBSI V2 Flatpickr theme — accent color, DM Sans font, dark mode support',
      'filterDate nav sync — btnPrevDate/btnNextDate/btnToday trigger requestAnimationFrame sync',
      'Native date input retained as hidden form value source — all business logic unchanged',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-06-07',
    summary: 'PBSI Select Component',
    highlights: [
      'Custom PBSI Select replaces all 6 browser-native <select> dropdowns',
      'Targets: #fieldDriver, #fieldVehicle, #requestFieldDriver, #requestFieldVehicle, #userFieldRole, #v2AdminRoleFilter',
      'Portal-rendered floating panel (z-index 350) — escapes modal stacking contexts',
      'MutationObserver syncs option list when Firebase repopulates driver/vehicle options at runtime',
      'Full keyboard navigation: Arrow keys, Enter/Space to pick, Escape/Tab to close',
      'aria-activedescendant pattern — focus stays on trigger, screen reader announces highlighted option',
      'Dark mode and mobile touch support (font-size: 16px on ≤600px prevents iOS Safari zoom)',
      'Native <select> retained as hidden form value source — all business logic unchanged',
    ],
  },
  {
    version: '1.3.4',
    date: '2026-06-07',
    summary: 'Operational Data Accuracy Fix',
    highlights: [
      'Passenger count minimum changed from 1 to 0 — supports logistics/equipment assignments with no passengers',
      'Fixed || 1 fallback that silently swallowed pax=0 as "1" on form submit',
      'Request approval default pax changed from 1 to 0',
      'Reimbursement form: a.pax || 1 replaced with a.pax ?? 0 — equipment runs now print "0 pax" correctly',
      'Assignment detail and WA copy: null-safe a.pax ?? 0 guards against legacy missing-field data',
    ],
  },
  {
    version: '1.3.3',
    date: '2026-06-07',
    summary: 'Native Component Replacement Sprint I',
    highlights: [
      'PBSI Stepper — passenger count (#fieldPax) replaced with [−] N [+] component (affordance restored)',
      'Search icon — PBSI glass icon added to admin workspace search input (light + dark mode)',
      'Toggle consolidation — #userFieldActive migrated from legacy .toggle-switch to .pbsi-toggle-input',
      'Comment character counter — live 0 / 500 counter with warn (450+) and full (500) color states',
    ],
  },
  {
    version: '1.3.2',
    date: '2026-06-07',
    summary: 'V2 UI Consistency Sprint',
    highlights: [
      'Custom select chevron — native OS dropdown arrow replaced with V2 SVG chevron (light + dark mode)',
      'Number input spinners hidden — consistent with odometer field; no browser-native arrows visible',
      'Textarea resize handle removed — resize: none locks modal layout containment',
      'Selectable card checkboxes — Multi Hari / Penuh Hari redesigned as PBSI V2 card components',
      'Calendar picker indicator hidden — date field click still opens native picker',
      'Date input color-scheme unified — all five date inputs now consistently force light picker',
      'Placeholder contrast upgraded — #757575 (~4.4:1) replaces browser default on form inputs',
      'Browser validation bubbles suppressed — novalidate confirmed on all forms; JS validation engine active',
    ],
  },
  {
    version: '1.3.1',
    date: '2026-06-07',
    summary: 'User Management Enhancement',
    highlights: [
      'User list grouped by role: Admin → Bidang → Driver → Viewer (Engineering future-ready)',
      'Alphabetical sorting within each role group (A→Z by display name)',
      'Collapsible role groups with session-state memory (Admin expanded by default)',
      'Role count badge per group header',
      'Statistics header: Total Users + per-role counts (Admin, Bidang, Driver, Viewer)',
      'Notification ownership system — driver-scoped Telegram notifications',
      'Sticky notification footer on assignment detail modal',
      'Form guard — data loss prevention with confirmation dialog on unsaved changes',
      'Default date = today on initial load',
    ],
  },
  {
    version: '1.2.5',
    date: '2026-06-04',
    summary: 'Reimbursement Form — Production Polish',
    highlights: [
      'Sequential document numbering: PBSI/RMB/YYYY/MM/NNNN (atomic Firebase counter, resets monthly)',
      'No. Assignment reference displayed in form header (ASG-YYYYMMDD-XXXXXX)',
      'Section C redesigned: 35/65 two-column — driver statement + reimbursement breakdown table',
      'Section D simplified: blank dashed area for physical receipt attachment',
      'Role permission gate: reimbursement form hidden for Bidang/Viewer/other non-driver roles',
      'Button loading state during async document number acquisition',
      'Vehicle plate displays "-" gracefully when not yet configured',
      'Overtime logic verified: NORMAL (09:00–17:00) vs LEMBUR unchanged',
    ],
  },
  {
    version: '1.2.4',
    date: '2026-06-04',
    summary: 'Reimbursement Form Generator',
    highlights: [
      'Print Reimbursement Form action added to Assignment Detail Modal',
      'Professional A4 form: driver info, odometer, overtime status, signatures',
      'Overtime auto-calculated: NORMAL (09:00–17:00) vs LEMBUR (outside window)',
      'Section D: Lampiran Bukti Pengeluaran attachment area (≈35% of page)',
      'Browser Print / Save as PDF support (no external library)',
      'VEHICLE_PLATES map added to drivers.js for future plate number population',
      'Requester field: Bidang for request-based, PIC/Admin for direct assignments',
      'Architecture ready for fuel, toll, parking reimbursement expansion',
    ],
  },
  {
    version: '1.2.3',
    date: '2026-06-02',
    summary: 'Completion Tracking Expansion',
    highlights: [
      'createdBy field added to all assignment types',
      'Request-based: createdBy = requester (bidang), distinct from approvedBy (admin)',
      'Direct admin: createdBy = admin who created the assignment',
      'getAssignmentLifecycle() helper — foundation for Analytics v1.2.5',
      'validateLifecycle() — warns on out-of-order timestamps',
      'lifecycle validator added to ValidationRegistry',
      'Detail modal: "Diminta oleh" row for request-based assignments',
      'odometer fields (startOdometer, endOdometer, distanceTravelled) initialized to null on creation',
    ],
  },
  {
    version: '1.2.2',
    date: '2026-06-02',
    summary: 'Odometer Foundation',
    highlights: [
      'KM Awal captured on Start Assignment via odometer modal',
      'KM Akhir captured on Complete Assignment via odometer modal',
      'distanceTravelled calculated automatically',
      'startOdometer, endOdometer, distanceTravelled stored in Firebase',
      'KM Awal / KM Akhir / Jarak Tempuh shown in assignment detail',
      'validateOdometer wired from Validation Engine (v1.2.1)',
      'Stacked modal UX — detail modal stays visible during input',
    ],
  },
  {
    version: '1.2.1',
    date: '2026-06-02',
    summary: 'Validation Engine Foundation',
    highlights: [
      'Centralized Validation Engine (js/validation.js)',
      'ValidationRegistry — extensible validator dispatch',
      'Request, Assignment, Driver, Vehicle, User validators',
      'Odometer Validator foundation (not yet active)',
      'Multi Day + Full Day combination support',
      'Full Day: time inputs dimmed instead of hidden',
      'WA Copy: bold title + PIC in header',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-05-31',
    summary: 'Mobile UX Refresh & Schedule Navigation Improvement',
    highlights: [
      'Navigation redesign with collapsible sidebar',
      'Horizontal timeline mouse-wheel scrolling',
      'Mobile bottom navigation',
      'Centralized version management',
      'Enterprise-grade header redesign',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-05-01',
    summary: 'Initial release',
    highlights: [
      'Driver schedule management',
      'Request workflow (bidang → admin)',
      'Firebase real-time sync',
      'Telegram push notifications',
    ],
  },
];
